[workspace]
resolver = "2"
members = ["gme", "msg", "sdk"]

[workspace.dependencies]
msg = { path = "msg/" }

[profile.release]
strip = true
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"

[profile.release.build-override]
strip = true
opt-level = "z"
codegen-units = 1
