[package]
name = "gme"
version = "0.1.0"
edition = "2021"

[dependencies]
smol = "2.0.2"
msg.workspace = true
prost = "0.13.3"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
prost-types = "0.13.4"
